# This GitHub Actions workflow file defines a CI/CD pipeline with SonarQube integration

name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger the workflow on changes to the 'main' branch

jobs:
  checkout:
    name: Checkout Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Action to checkout code from the repository

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: checkout # Ensure the checkout job completes before this job runs
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Specify the Java version
          distribution: 'adopt-openjdk'
      
      - name: Build with Maven
        run: mvn clean install # Build the project using Maven

  sonarqube-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: build # Ensure the build job completes before this job runs
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Action to checkout code from the repository

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Specify the Java version
          distribution: 'adopt-openjdk'
        
      - name: SonarQube Scanner
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: mvn sonar:sonar -Dsonar.host.url=${{ secrets.SONARQUBE_URL }} -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }} # Run SonarQube analysis

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: sonarqube-analysis # Ensure the SonarQube analysis job completes before this job runs
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Action to checkout code from the repository

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Specify the Java version
        
